version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app
        container_name: nginx

    app:
        image: php:8.2-fpm
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: app
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        volumes:
            - ./tmp/db:/var/lib/postgres
        environment:
            POSTGRES_DB: test
            POSTGRES_PASSWORD: 1234
            POSTGRES_USER: user
        ports:
            - '8101:3306'
        container_name: db
